// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUzlo2KYEUOr0hnBDYrx0uT4ysmlE_VQ',
    appId: '1:278272433968:web:dd0dbf2e1717e47be1b2f5',
    messagingSenderId: '278272433968',
    projectId: 'amadia-notebook',
    authDomain: 'amadia-notebook.firebaseapp.com',
    storageBucket: 'amadia-notebook.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiLLX4URxmc3Lh9srmkDhp1BipoGfpKGE',
    appId: '1:278272433968:android:7d81067acfe03153e1b2f5',
    messagingSenderId: '278272433968',
    projectId: 'amadia-notebook',
    storageBucket: 'amadia-notebook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQLI2jPvwgBjWKA5FBdPgnNc6JeoUkDA',
    appId: '1:278272433968:ios:cd74f7e1310737aee1b2f5',
    messagingSenderId: '278272433968',
    projectId: 'amadia-notebook',
    storageBucket: 'amadia-notebook.appspot.com',
    iosClientId: '278272433968-c0p7jg10t1ekep0vvss5k1n2qj0i9dgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQLI2jPvwgBjWKA5FBdPgnNc6JeoUkDA',
    appId: '1:278272433968:ios:cd74f7e1310737aee1b2f5',
    messagingSenderId: '278272433968',
    projectId: 'amadia-notebook',
    storageBucket: 'amadia-notebook.appspot.com',
    iosClientId: '278272433968-c0p7jg10t1ekep0vvss5k1n2qj0i9dgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes',
  );
}
